from typing import Any, Generic, Iterable, Mapping, TypeVar, overload

_T = TypeVar('_T')
_K = TypeVar('_K')
_V = TypeVar('_V')

class _IntPrim(int):
    def __add__(self, other: int, /) -> 'Self': ...
    def __sub__(self, other: int, /) -> 'Self': ...
    def __mul__(self, other: int, /) -> 'Self': ...
    def __floordiv__(self, other: int, /) -> 'Self': ...
    def __mod__(self, other: int, /) -> 'Self': ...
    def __and__(self, other: int, /) -> 'Self': ...
    def __or__(self, other: int, /) -> 'Self': ...
    def __xor__(self, other: int, /) -> 'Self': ...
    def __lshift__(self, other: int, /) -> 'Self': ...
    def __rshift__(self, other: int, /) -> 'Self': ...
    def __neg__(self) -> 'Self': ...
    def __pos__(self) -> 'Self': ...
    def __invert__(self) -> 'Self': ...
    def __lt__(self, other: int, /) -> 'cbool': ...
    def __le__(self, other: int, /) -> 'cbool': ...
    def __gt__(self, other: int, /) -> 'cbool': ...
    def __ge__(self, other: int, /) -> 'cbool': ...
    def __eq__(self, other: object, /) -> 'cbool': ...
    def __ne__(self, other: object, /) -> 'cbool': ...


class _FloatPrim(float):
    def __add__(self, other: float, /) -> 'Self': ...
    def __sub__(self, other: float, /) -> 'Self': ...
    def __mul__(self, other: float, /) -> 'Self': ...
    def __truediv__(self, other: float, /) -> 'Self': ...
    def __mod__(self, other: float, /) -> 'Self': ...
    def __neg__(self) -> 'Self': ...
    def __pos__(self) -> 'Self': ...
    def __lt__(self, other: float, /) -> 'cbool': ...
    def __le__(self, other: float, /) -> 'cbool': ...
    def __gt__(self, other: float, /) -> 'cbool': ...
    def __ge__(self, other: float, /) -> 'cbool': ...
    def __eq__(self, other: object, /) -> 'cbool': ...
    def __ne__(self, other: object, /) -> 'cbool': ...


class int64(_IntPrim): ...
class int32(_IntPrim): ...
class int16(_IntPrim): ...
class int8(_IntPrim): ...
class uint64(_IntPrim): ...
class uint32(_IntPrim): ...
class uint16(_IntPrim): ...
class uint8(_IntPrim): ...
class double(_FloatPrim): ...
class float64(_FloatPrim): ...
class float32(_FloatPrim): ...
class cbool(_IntPrim): ...

class CheckedList(list[_T], Generic[_T]):
    def __init__(self, items: Iterable[_T] = ...) -> None: ...


class CheckedDict(dict[_K, _V], Generic[_K, _V]):
    def __init__(self, items: Mapping[_K, _V] = ...) -> None: ...

chklist = CheckedList
chkdict = CheckedDict

@overload
def cast(typ: type[_T], val: object) -> _T: ...
@overload
def cast(typ: Any, val: object) -> Any: ...

def box(val: object) -> object: ...
def unbox(val: object) -> object: ...
def clen(c: object) -> int: ...

def inline(f: _T) -> _T: ...
def final(f: _T) -> _T: ...
def dynamic_return(f: _T) -> _T: ...

def native(so_path: str): ...

class StaticGeneric(Generic[_T]): ...
